# Generated by Django 5.1.5 on 2025-02-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi_cam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigi_cam.persona'),
        ),
    ]
