# Generated by Django 5.1.5 on 2025-02-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigi_cam', '0004_registroacceso_reconocido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacceso',
            name='reconocido',
        ),
    ]
